from pygame import image, Rect, math
from pygame_gui.elements import UIImage
from game.core.csv_support import cut_graphics 
from game.core.constants import *

# The main class that each tile is using so that they can be rendered on the board map
class Tile(UIImage):
    def __init__(self, start_pos, tiles_size, img_path, manager, container=None, tile=None):
        relative_pos= (start_pos[0] * tiles_size[0], start_pos[1] * tiles_size[1])
        relative_rect = Rect(relative_pos, tiles_size)
        
        self.img = image.load(f'game/assets/{img_path}').convert_alpha()
        if tile == None:
            loaded_image = self.img
        else:
            self.sprite_list = cut_graphics(self.img)
            loaded_image = self.sprite_list[tile]

        super().__init__(relative_rect=relative_rect, image_surface=loaded_image, manager=manager, container=container)

class Player(Tile):
    def __init__(self, start_pos, tiles_size, manager, map_tiles, container=None, tile=None):
        # Ive put the img_path in here cause its not something that 'should' be changed on the fly as animations can break if changed as of now
        img_path='SproutLands/Characters/Basic Charakter Spritesheet.png'
        super().__init__(start_pos, tiles_size, img_path, manager, container, tile)

        self.vel = math.Vector2(0,0)
        self.map_tiles = map_tiles

        self.animationcount = 0
        self.animations = {}
        self.state = 'idle'

        self.is_jumping = False
        self.jump_timer = 0

        self._set_animations()

    def _set_animations(self):
        animation_frames = {
            "down":  [0, 1, 2, 3],
            "up":    [4, 5, 6, 7],
            "left":  [8, 9, 10, 11],
            "right": [12, 13, 14, 15],
            "idle": [0, 1],
            "jump": [0]
        }

        animation_list = self._load_animations(sprite_col_start=1,
                              sprite_row_start=1,
                              sprite_gap=2)
        
        for name, frames in animation_frames.items():
            self.animations[name] = []
            for frame in frames:
                self.animations[name].append(animation_list[frame])

    def _load_animations(self, sprite_col_start, sprite_row_start, sprite_gap):
        # this function is basically just for getting rid of blank tiles generated by 'core/csv_support.py'
        # as if you use a image that doesnt have any blank gaps, and set all values to 0 then it just returns a 0-x list with no steps

        total_tiles_per_row = self.img.get_height() // IMG_TILE_SIZE
        total_tiles_per_col = self.img.get_width() // IMG_TILE_SIZE

        frames = [] 
        for start_col in range(sprite_row_start, total_tiles_per_row, 1+sprite_gap):
            col = total_tiles_per_row * start_col
            for start_row in range(sprite_col_start, total_tiles_per_col, 1+sprite_gap):
                frame_index = col + start_row
                frames.append(frame_index)

        return frames
    
    def do_action(self, action = ""):
        match action:
            case "up":
                self.vel.y = -PLAYER_VEL
                self.state = action
            case "down":
                self.vel.y = PLAYER_VEL
                self.state = action
            case "left":
                self.vel.x = -PLAYER_VEL
                self.state = action
            case "right":
                self.vel.x = PLAYER_VEL
                self.state = action
            case "jump":
                if not self.is_jumping:
                    self.is_jumping = True
                    self.jump_timer = JUMP_DURATION
                    self.state = action
            case "idle":
                self.vel.x = 0
                self.vel.y = 0
                self.state = action

    def update_jump(self):
        if not self.is_jumping:
            return 0

        self.jump_timer -= 1
        #seems like only odd numbers work for the JUMP_DURATION, or else it goes further down than started from
        half = JUMP_DURATION // 2

        if self.jump_timer > half:
            progress = (JUMP_DURATION - self.jump_timer) / half
            offset = progress
        else:
            progress = self.jump_timer / half
            offset = -progress

        jump_offset = int(JUMP_HEIGHT * offset)

        if self.jump_timer <= 0:
            self.is_jumping = False
            self.state = 'idle'
            jump_offset = 0

        self.rect.y -= jump_offset

    def update_velocity(self, vel):    
        self.rect.x += int(vel.x)
        self.rect.y += int(vel.y)

    def update_pos_collision(self, collisions):
        if self.vel.x == 0 and self.vel.y == 0 and not self.is_jumping:
            return
        
        for collision in collisions:
            for sprite in self.map_tiles[collision]:
                if self.rect.colliderect(sprite.rect):
                    overlap_x = min(self.rect.right, sprite.rect.right) - max(self.rect.left, sprite.rect.left)
                    overlap_y = min(self.rect.bottom, sprite.rect.bottom) - max(self.rect.top, sprite.rect.top)
                    if overlap_x < overlap_y:
                        if self.vel.x > 0:
                            self.rect.right = sprite.rect.left
                        elif self.vel.x < 0:
                            self.rect.left = sprite.rect.right
                        self.vel.x = 0
                    if overlap_y < overlap_x:
                        if self.vel.y > 0:
                            self.rect.bottom = sprite.rect.top
                        elif self.vel.y < 0:
                            self.rect.top = sprite.rect.bottom
                        self.vel.y = 0
       
    def update_sprite_sheet(self):
        time_lag = 10
        current_strip = self.animations[self.state]

        frame_index = (self.animationcount // time_lag) % len(current_strip)
        tile_number = current_strip[frame_index]
        self.set_image(self.sprite_list[tile_number])
        self.animationcount += 1

    def update(self, delta_time):
        super().update(delta_time)
        self.update_velocity(self.vel)
        self.update_pos_collision(['water', 'tree'])
        self.update_jump()
        self.update_sprite_sheet()
         