from pygame import Color, image
from pygame_gui.elements import UIImage

class BaseEnvironment:
    def __init__(self, title: str, background: str, theme: str | None = None):
        self.title = title

        path = f'game/assets/{background}'
        self.background_img = image.load(path).convert()
        
        self.theme_path = f"game/themes/{theme}.json"

    def create_ui(self, ui_manager):
        pass

    def on_ui_event(self, event):
        # Hook for UI-only events generated by pygame_gui.
        pass

    def update_frame(self, delta_time):
        # Per-frame updates (e.g., typing effects, animations).
        pass
    
    def render_background(self):
        display = self.game_manager.display
        image_rect = self.background_img.get_rect()
        image_rect.width = display.resolution[0]
        image_rect.height = display.resolution[1]
        UIImage(relative_rect=image_rect, image_surface=self.background_img, manager=display.ui_manager)
            

    # Passes the game manager so that environmennts can switch to other environments
    def set_manager(self, manager):
        self.game_manager = manager
