from game.core.constants import *

from csv import reader
from pygame import image, Surface, Rect

# Loads level csv in 'environments/map/{map_path}.CSV' to be used  
def import_map_layout(path):
    terrain_map = []
    with open(f"game/environments/map/{path}.csv") as map:
        level = reader(map,delimiter = ',')
        for row in level:
            terrain_map.append(list(row))
        return terrain_map
    
# Gets a image and crops it at a tile to return to use for rendering
def cut_graphics(surface):

    # IMG_TILE_SIZE is the size of each SproutLand asset, eg 16x16
    # So if we use another graphics that dont match 16x16 for the tiles, this needs to be changed
    tile_num_x = int(surface.get_size()[0] / IMG_TILE_SIZE)
    tile_num_y = int(surface.get_size()[1]/ IMG_TILE_SIZE)

    cut_tiles = []
    for row in range(tile_num_y):
        for col in range(tile_num_x):
            x = col * IMG_TILE_SIZE
            y = row * IMG_TILE_SIZE
            new_surf = Surface((IMG_TILE_SIZE,IMG_TILE_SIZE)).convert_alpha()
            new_surf.blit(surface,(0,0),Rect(x,y,IMG_TILE_SIZE,IMG_TILE_SIZE))
            new_surf.set_colorkey('black')
            cut_tiles.append(new_surf)
    
    return cut_tiles

def tile_graphics(img_surface, sprite_col_start, sprite_row_start, sprite_gap):
        # this function is basically just for getting rid of blank tiles generated by 'core/csv_support.py'
        # as if you use a image that doesnt have any blank gaps, and set all values to 0 then it just returns a 0-x list with no steps

        total_tiles_per_row = img_surface.get_height() // IMG_TILE_SIZE
        total_tiles_per_col = img_surface.get_width() // IMG_TILE_SIZE

        frames = [] 
        for start_col in range(sprite_row_start, total_tiles_per_row, 1+sprite_gap):
            col = total_tiles_per_row * start_col
            for start_row in range(sprite_col_start, total_tiles_per_col, 1+sprite_gap):
                frame_index = col + start_row
                frames.append(frame_index)

        return frames